### ISSUE TITLE
Query domain could be inmutable

### ISSUE THREAD

**Issue by amatmv** [gisce/ooquery#19]
This line is modifying the query domain given to the parser of the *where* clause and leaving it **empty**.
https://github.com/gisce/ooquery/blob/1e0b66e642453b4a3a28246703df5521f3ef1c20/ooquery/parser.py#L97

This makes that a query coded like this to fail.
```python
params = [('id', 'in', (1,2,3,4))]
sql = OOQuery(self, cursor, uid).select(['name']).where(params)
assert params, "Params are empty!"
```

To avoid unexpected behavior, the could be done by consulting the query params instead of emptying it.

**Comment by ecarreras** [comment]
Please review your version of OOquery, because https://github.com/gisce/ooquery/pull/17 should fixed it. Versions >= 0.12.1 are fixed

**Comment by amatmv** [comment]
Uops, my fault. Thank you.
