### ISSUE TITLE
Evalua "0" com a "None" en un search

### ISSUE THREAD

**Issue by eberloso** [gisce/ooquery#30]
Cas real trobat:

```python
inv_obj = self.pool.get('account.invoice')
search_params = [
    ('pending_state.active', '=', True),
    ('pending_state.pending_days', '>', 0),
    ('type', '=', 'out_invoice'),
    ('state', '=', 'open')
]
q = OOQuery(inv_obj, cursor, uid)
sql = q.select(['id']).where(search_params)
```
Si es mira el valor de `sql` (fent un `list(sql)`) es veu que el valor dels parametres que es passen son els següents:
```python
(True, None, 'out_invoice', 'open')
```

S'ha transformat el `0` a un `None`. Llavors el postgres no troba els registres en que el camp `pending_days` siguin `> 0` ja que en realitat executa  `INTEGER > NULL`  que sempre és `False`.

**Comment by ecarreras** [comment]
No és una issue de ooquery sinó de la implementació de ooquery per l'ERP que evalua False com a None. S'ha d'arreglar a l'herència que fa l'orm de l'ERP.
